# Generated by Django 5.0.6 on 2024-05-26 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static_uploads/')),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[(1, 'Blue'), (2, 'Yellow'), (3, 'Red')], max_length=2)),
            ],
        ),
    ]
